analyzer:
  exclude: [ build/**, lib/**.freezed.dart, lib/**/*.g.dart, lib/**/*.gr.dart, passkeys/**, lib/**/*.config.dart ]
linter:
  rules:
    prefer_relative_imports: true
    always_use_package_imports: false
    public_member_api_docs: false
    require_trailing_commas: true
    