name: product_manager_demo
description: "Flutter product manager demo project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.0
  get_it: ^8.1.0
  http_mock_adapter: ^0.6.1
  injectable: ^2.3.2
  intl: ^0.20.2
  meta: ^1.11.0
  path: ^1.9.1
  path_provider: ^2.1.4
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.3.2
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/mock_data/
